# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20181031_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Enrolled_students', models.ManyToManyField(to='student.Profile')),
            ],
        ),
    ]
