# Generated by Django 2.1.3 on 2018-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Enrolled_students',
        ),
        migrations.AddField(
            model_name='course',
            name='Max_Grades',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='course',
            name='Study_Years',
            field=models.IntegerField(default=1),
        ),
    ]
