# Generated by Django 2.1.3 on 2019-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hmsuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMSProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, unique=True)),
                ('national_id', models.CharField(max_length=16, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('type', models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('R', 'Receptionist')], default='P', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='hmsuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='hmsuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='HMSUser',
        ),
    ]
