# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('year', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
