# Generated by Django 2.1.3 on 2019-02-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmsuser',
            name='type',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('R', 'Receptionist')], default='P', max_length=16),
        ),
    ]
