# Generated by Django 2.1.3 on 2019-02-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190202_1811'),
    ]

    operations = [
    ]
