# Generated by Django 2.1.3 on 2019-02-03 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_hmsprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('A', 'Analysis'), ('R', 'Rays'), ('E', 'Examination')], default='E', max_length=30)),
                ('content', models.TextField(null=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report2', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
