# Generated by Django 2.1.3 on 2019-02-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='initiator',
        ),
    ]
