# Generated by Django 2.1.3 on 2019-02-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190203_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Pharmacy'),
        ),
    ]
