# Generated by Django 2.1.3 on 2019-02-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='users.HMSProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.HMSProfile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.HMSProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='users.Pharmacy'),
        ),
    ]
