# Generated by Django 2.1.3 on 2018-11-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('national_id', models.PositiveIntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
