# Generated by Django 2.1.3 on 2018-11-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
