# Generated by Django 2.1.3 on 2018-11-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manager', '0002_auto_20181125_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
