# Generated by Django 2.1.3 on 2018-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manager', '0003_auto_20181125_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
